server:
   port: 8080
   tomcat:
     min-spare: 25
     max-threads: 750
spring:
  application:
     name: java-voltage-simple-api

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: info,refresh,health,bus-refresh,busrefresh

  endpoint:
    refresh:
      enabled: true
config:
  datasource:
    KeyDatasource:
      Enabled: true
      IdleTimeout: 900000
      JdbcUrl: jdbc:postgresql://20.64.178.18:5432/postgres #192.168.181.133 172.10.10.22 172.18.242.22 #voltage
      Username: postgres
      MaxLifetime: 1800000
      TestQuery: SELECT 1
      Password: Ranger123! #123123
      MinimumIdle: 1
      DriverClass: org.postgresql.Driver
      PoolName: KeyDatasource
      MaximumPoolSize: 200
      AutoCommit: true
      ConnectionTimeout: 500