server:
   port: 8084
   tomcat:
     min-spare: 25
     max-threads: 750
spring:
  application:
     name: tyk-voltage-plugin

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: info,refresh,health,bus-refresh,busrefresh

  endpoint:
    refresh:
      enabled: true
config:
  voltage:
    PolicyUrl: https://voltage-pp-0000.voltage.development.co.id/policy/clientPolicy.xml
    TrustStorePath: /opt/voltage/simpleapi/trustStore-cloud
    CachePath: /opt/voltage/simpleapi/cache
    Identity: admin@voltage.development.co.id
    SharedSecret: mantap100%
    AlphanumericFormat: alphanumeric
    NumericFormat: numeric
    AlpaFormat: alpha
    ClientId: Simple_API_Java_Date_Sample
    ClientIdVersion: 6.22.0.0
  datasource:
    KeyDatasource:
      Enabled: true
      IdleTimeout: 900000
      JdbcUrl: jdbc:postgresql://192.168.181.133:5435/DEV_TYK #192.168.181.133 #172.10.10.22
      Username: tyk_user
      MaxLifetime: 1800000
      TestQuery: SELECT 1
      Password: devtyk1#!
      MinimumIdle: 1
      DriverClass: org.postgresql.Driver
      PoolName: KeyDatasource
      MaximumPoolSize: 200
      AutoCommit: true
      ConnectionTimeout: 500