server:
   port: 8084
   tomcat:
     min-spare: 25
     max-threads: 750
spring:
  application:
     name: tyk-voltage-plugin
  kafka:
    bootstrap-servers: localhost:19091,localhost:19092,localhost:19093
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      batch-size: 64KB
      buffer-memory: 64MB
      linger-ms: 10
      max-block-ms: 60000
      retries: 10
    listener:
      ack-mode: record
  
    properties:
      schema:
        registry:
          url: ${SCHEMA_REGISTRY_URL:http://localhost:6969}

logging:
  level:
    root: INFO
    org:
      apache:
        kafka:
          clients:
            NetworkClient: WARN

management:
  endpoints:
    web:
      exposure:
        include: info,refresh,health,bus-refresh,busrefresh

  endpoint:
    refresh:
      enabled: true
config:
  voltage:
    PolicyUrl: https://voltage-pp-0000.opentext.co.id//policy/clientPolicy.xml
    TrustStorePath: /opt/voltage/simpleapi/trustStore-cloud
    CachePath: /opt/voltage/simpleapi/cache
    Identity: developer@ori.co.id
    SharedSecret: voltage123
    AlphanumericFormat: alphanumeric
    NumericFormat: numeric
    AlpaFormat: alpha
    ClientId: Simple_API_Java_Date_Sample
    ClientIdVersion: 6.22.0.0
  datasource:
    KeyDatasource:
      Enabled: true
      IdleTimeout: 900000
      JdbcUrl: jdbc:postgresql://20.64.178.18:5432/postgres?currentSchema=public #192.168.181.133 #172.10.10.22
      Username: postgres
      MaxLifetime: 1800000
      TestQuery: SELECT 1
      Password: Ranger123! #devtyk1#!
      MinimumIdle: 1
      DriverClass: org.postgresql.Driver
      PoolName: KeyDatasource
      MaximumPoolSize: 200
      AutoCommit: true
      ConnectionTimeout: 500
  kafka:
    topic-name: voltage-logs
    graylog-topic-name: gray-logs